# Generated by Django 4.2.2 on 2023-06-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashierPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code_product',
            field=models.CharField(auto_created=True, blank=True, max_length=100, null=True),
        ),
    ]
