# Generated by Django 4.2.2 on 2023-06-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashierPage', '0002_alter_product_code_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code_product',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
