# Generated by Django 4.2.2 on 2023-06-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashierPage', '0003_alter_product_code_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
