# Generated by Django 4.2.2 on 2023-06-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashierPage', '0006_pra_checkout_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='pra_checkout',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='product',
            field=models.ManyToManyField(blank=True, to='cashierPage.pra_checkout'),
        ),
    ]
