# Generated by Django 4.2.2 on 2023-06-17 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashierPage', '0008_pra_checkout_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='product',
        ),
        migrations.AddField(
            model_name='checkout',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashierPage.pra_checkout'),
        ),
    ]
