# Generated by Django 4.2.2 on 2023-06-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashierPage', '0009_remove_checkout_product_checkout_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pra_checkout',
            name='Product',
        ),
        migrations.AddField(
            model_name='pra_checkout',
            name='Product',
            field=models.ManyToManyField(blank=True, null=True, to='cashierPage.product'),
        ),
    ]
